services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: news-intelligence-collector

    restart: unless-stopped

    env_file:
      - .env

    networks:
      - backend


networks:
  backend:
    external: true